### ISSUE TITLE
Gatsby Site

### ISSUE THREAD

**Issue by akzhy** [infincek/CEK-website#10]
New gatsby site is under development.
Should I create a new repository or create a branch ?

**Comment by athul** [comment]
@akzhy Thanks for Opening the Issue... :sparkling_heart:   I would really recommend a new repo as it wouod give us more independence in working only on that (working on branches with another codebase is frustrating).
Plus apart from personal repositories I'd suggest a **new organisation or existing one** (like the open source community) for the repos. @samanyuneelson What do you say? Could we put these repos in another org than a personal one??

**Comment by athul** [comment]
Plus the Open Source Community organisation is made for you guys..  I think both of you are admins there.
Ping for any queries on transferring the repo or anything like that.

**Comment by akzhy** [comment]
Okay.
Lets here @samanyuneelson 's opinion too.

**Comment by athul** [comment]
Yes

-------- Original Message --------

**Comment by athul** [comment]
We should make a discussion channel on this development things... A WhatsApp group or telegram group something like that...

-------- Original Message --------

**Comment by akzhy** [comment]
I am okay with either, choose one and create it

**Comment by samanyuneelson** [comment]
I had made the organisation

**Comment by samanyuneelson** [comment]
Would forking the repo ad it to the organisation

**Comment by athul** [comment]
Nope... Transfer to the organization from the repo settings

**Comment by samanyuneelson** [comment]
Wokay

**Comment by athul** [comment]
Add us to the org too... As Admins :p
