### ISSUE TITLE
Descrepancy in images

### ISSUE THREAD

**Issue by athul** [infincek/CEK-website#8]
I mean... Why is Captain Americ's Image here as Principal.jpg?🙄🙄🤔🤔🤔
I'll add some lavels to make this issue colorful :octocat:

**Comment by GokulDas027** [comment]
Placeholders maybe.., we have to care about it only at time of deployment 🤷

**Comment by akzhy** [comment]
Placeholder images
Will be replaced by actual ones when we get them

**Comment by athul** [comment]
Look how colourful the issue is....    Putting up issues and working on them will make the working tree a lot more sense and efficient.. People use issues the whole time for every thing. Funny Thing is that GitHub uses issues to manage their things and also for **Wedding Planning**
